# Generated by Django 4.0.4 on 2022-04-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_time', models.DateTimeField(auto_now_add=True)),
                ('update_time', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=15, unique=True)),
                ('password', models.CharField(max_length=255)),
                ('nickname', models.CharField(max_length=15, unique=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
