# Generated by Django 4.0.4 on 2022-04-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Donator',
            new_name='Supporter',
        ),
        migrations.RemoveField(
            model_name='product',
            name='donators',
        ),
        migrations.AddField(
            model_name='product',
            name='supporters',
            field=models.ManyToManyField(blank=True, null=True, related_name='products', through='products.Supporter', to='users.user'),
        ),
        migrations.AlterModelTable(
            name='supporter',
            table='supporters',
        ),
    ]
