# Generated by Django 4.0.4 on 2022-04-16 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_rename_funding_per_session_product_support_per_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='supporter',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
    ]
