# Generated by Django 4.0.4 on 2022-04-16 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_rename_productdetail_detail_alter_product_delete_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detail',
            name='achievment_rate',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
